---
title: "Shared Bike Usage Study"
subtitle: "real-time prediction of bicycle riding-time in the big data setting"
author: "Bangyao Zhao, Xuemei Ding, Sunyi Chi"
date: "2019/12/22"
output:
  prettydoc::html_pretty:
   highlight: github
   theme: hpstr
  html_document: default
---
```{r include=FALSE}
library(bigmemory)
library(biganalytics)
```
The report is clearly written and sufficiently introduces the dataset of choice, the question of interest, the approach taken, and the results.
# Introduction
Bicycle sharing programs are getting popular today. They offer a convenient and affordable way to get around the city for both residents and tourists. Riding a bicycle is a fun exercise, and it is an environment-friendly transportation.

The Divvy Bikes is a bike sharing program in Chicago, Illinois. 6,131 bicycles can be rented from and return to 620 stations. Given that the number of bicycles at each station is relatively limited, it is meaningful to predict the renting time of each bicycle so as to reasonably arrange the resting bicycles.

Our project aims to predict the trip duration time of each Divvy Bike trip in 2018 using a set of covariates that can be abtained at the start of the trip, including information of the trip itself (time and start place) and the user (gender, age, and membership type).

# Data Description and Pre-processing
The dataset we used was the Divvy data set, which contained Divvy Bikes’ using information in 2018. 2,981,032 samples (trips) were recorded. For each trip, there was information of start and end time and station, as well as information of the user. The original variables are shown in the following table:

Variable name    | Variable label
-----------------|---------------
trip_id          | trip ID
tripduration     | end_time - start_time, in minutes.
Age              | age of user
from_station_name| name of the station where the trip starts. There are 620 different stations.                              
usertype         | user type. Can be either subscriber (Annual Members) or customer (users who bought single ride or one-day pass)
Gender           | gender of the user
Season           | in which season the trip took place.
start_time       | start date and time of the trip

To make full use of the variables, we extracted two variables from the original {start_time}, as shown below:

Variable name    | Variable label
-----------------|---------------
Start_time_cat   | in which time slot of a day the trip took place
weekends| indicator of whether the trip happens on weekends
# Approach and Results

## Linear Model

Linear regression is an approach to identify linear relationship between a response and explanatory variables. We use linear regression to start an exploratory research so as to identify significant predictors. 

$$tripduration=X\beta+\varepsilon,\ \varepsilon\sim N(0,\sigma^2)$$

### Memory issue

Our design matrix $X$ is of dimension $1490516\times 653$ due to the presence of categorical variables, which is too large to fit the matrix in the memory. When fitting the model, we were not able to fit the model by `lm()` function. We solve this problem by using the bigmemory package.

After successfully fitting the model, we looked at the residual plot

### Constant Variance issue

Let's have a look at the residuals:

```
res <- readRDS("../results/res.rds")
plot(res)
```

As we can see, the constant variance assumption seems violated in the model, so we decided to use transformation to fix the problem, we finally chose the square root function. 

### Results
```
res1 <- readRDS("../results/res1.rds")
summary(res1)
```
As we can see, even after fixing the transformation, the $R^2=0.0432$ is still unsatisfactory, which means linear model may not be a perfect fit for this problem, so we decide to switch to other advanced non-parametric machine learning models. 

